/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'kottalovag' at '2016.07.13. 10:25' with Gradle 2.14
 *
 * @author kottalovag, @date 2016.07.13. 10:25
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
